### ISSUE TITLE
[0.5pt] Find external API - group task

### ISSUE THREAD

**Issue by iamsjunaid** [iamsjunaid/js-capstone-2#20]
Find an API to base the development of the webapp around it. The API should allow you to
  - Get a list of items with a unique item id (or generate the unique id).
  - For a given item, get detailed information about it.
choose an APIs that doesn't need authentication. if you select an API that requires authentication, you should implement it on your own. Also, if you select an API that provides image resources your webapp will be more visual.

**Comment by topeogunleye** [comment]
Hi @iamsjunaid, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a JavaScript Kanban board project, that does not have link to their GitHub Kanban project or
information about the number of people in their group

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by topeogunleye** [comment]
@iamsjunaid, Kindly include information on:  

- the number of people in your group 
- link to your kanban project which is https://github.com/iamsjunaid/js-capstone-2/projects/1


<img width="598" alt="image" src="https://github.com/iamsjunaid/js-capstone-2/assets/52934128/9b7ed3f8-50df-4030-8b68-65689171903a">

**Comment by topeogunleye** [comment]
Hi @iamsjunaid, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a JavaScript Kanban board project, that does not include information on:  

- the number of people in your group 
- link to your kanban project which is https://github.com/iamsjunaid/js-capstone-2/projects/1


<img width="598" alt="image" src="https://github.com/iamsjunaid/js-capstone-2/assets/52934128/9b7ed3f8-50df-4030-8b68-65689171903a">




Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
